require:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: disable
Gemspec/RequireMFA:
  Enabled: false
Layout/LineLength:
  Enabled: false # FIXME enable me
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/VerifiedDoubleReference:
  Enabled: false
Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - HACK
    - NOTE
    - QUESTION
Style/Documentation:
  Enabled: false # FIXME enable me
