= WORKLOG

== TODO

* add empty front matter page in kf8 version if one is specified to allow navigation to first entry from TOC
* remove text justification hack (#92)
* why can't we navigate to first chapter on Kindle from TOC?
* add nav entry for cover if format != :kf8 ?
* cleanup this sanitize XML stuff; move to Asciidoctor::Helpers?
* allow role to be applied to chapter (which means the role must be on the document)
* make sure every doc is assigned an ID (perhaps it already is) so we don't need to rely on the docname attr as a fallback
* switch to epubcheck-ruby
 ** epubcheck-ruby 4.0.2
 ** supports options such as -q
 ** add -w option by default (perhaps allow additional options to be passed via the ebook-validate attribute)
* store spine as map in references?
* part vs chapter? a difference?

* create a video to demonstrate Google Play Books read aloud reading complete sentences in books generated with Asciidoctor EPUB3

.Gem
* Add step in `rake release` to set version back to *.dev
* enable NOKOGIRI_USE_SYSTEM_LIBRARIES=1 to speed up nokogiri install (in .travis.yml, bundler in general)
* Don't package sample documents (create separate folder in repo)

//^

.Converter
* CRITICAL: if document doesn't have doctitle, Untitled shows in epub2 TOC
* CRITICAL: conversion missing in epub3 backend for embedded (AsciiDoc table cell?)
* CRITICAL: revisit the headshot image logic
* CRITICAL: put e-book reader class on html instead of body
* CRITICAL: we're dropping subsequent paragraphs of preamble when abstract is found...need to pass them through
* CRITICAL: try to pull username from author email field; pull avatar from gravatar
* HIGH: cross references between chapters does not work (would it work if we used the smart cross reference syntax?)
* HIGH: add full table of contents to nav.xhtml, but use hidden below first level (check if works in Kindle); respect toclevels
* HIGH: if running on a single article, then the document id has a conflicting purpose
* HIGH: require spine option on include directive in order to create a chapter file (requires change in Asciidoctor)
* HIGH: move regexp to constants
* HIGH: use more thorough image path resolution
* HIGH: move navigation_document method to Packager
* HIGH: put shy marks after dashes to allow wrapping to occur in text justification
* MEDIUM: add landmarks nav list to nav.xhtml; see https://github.com/IDPF/epub3-samples/blob/master/31/moby-dick-mo-xhtml/EPUB/toc.xhtml
* MEDIUM: Kindle links to cover page when clicking on first chapter instead of first chapter page
* MEDIUM: auto-space button in btn macro, or add icon & icon placement as attributes on btn macro
* MEDIUM: move client sniffer JavaScript to file
* MEDIUM: use the dfn element for defining a definition of a term (not just term class); see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn
* MEDIUM: source highlighting using Rouge (instead of Pygments)
* QUESTION: add word joiner before inline tags too?
* we could detect Calibre by looking for the window.calibre_utils object
* packager doesn't resolve include files in subdirectory totally correctly
* implement checklists
* quiet flag
* upgrade to kindlegen 2.9.6 (only works for Ruby >= 2.0.0)

//^

.Packager
* HIGH: retain file name of original chapter file (otherwise, it can break interdoc xrefs)
* HIGH: add NOTICE.adoc to e-book archive
* HIGH: rework GEPUB so closures work more like in Prawn...perhaps using a wrapper
* HIGH: minimize CSS (and any other assets worth minimizing)
* HIGH: add back cover if specified
* MEDIUM: add JavaScript to nav.xhtml to add class for epubReadingSystem to body
* MEDIUM: rename OEBPS folder to EPUB
* MEDIUM: set modified date explicitly
* MEDIUM: use function to build and manipulate image paths
* MEDIUM: issue warning if front-cover-image doesn't match proper syntax
* MEDIUM: option to add nav.xhtml to navigation flow?
* support subtitle as separate from main title in package metadata
* support collection title in package metadata

.Fonts
* script to merge entypo icons from Font Icons into Font Awesome (name it font-awesomer.ttf)
* recreate ellipses in M+ 1p to be on baseline

.Stylesheet
* CRITICAL: padding around code in formal listing blocks
* CRITICAL: check style of level 5 and 6 headings (see Groovy docs)
* CRITICAL: use CSS3 filter scheme that allows admonitions to appear correctly on Google Play Books
  - see if Google Play books supports JavaScript and epubReadingSystem (no, but adds its own class to body)
* CRITICAL: use a following sibling selector for :first-line in abstract so it works when page is partitioned (e.g., in Google Play Books)
* CRITICAL: add support for different numbering systems (lowergreek, etc)
* HIGH: kindlegen no longer strips <header> elements, so we can drop our div wrapper hack
* HIGH: don't set text color so light on monochrome devices (use media query to detect)
* HIGH: make justify-text a class on body that can be controlled from AsciiDoc attribute (don't use word joiner in this case)
* HIGH: image border option (or add drop shadow to screenshots in README)
* HIGH: review the table border color
* HIGH: style example block
* HIGH: allow theme to be customized using stylesheet attribute
* MEDIUM: headshot has too much top margin when at top of page (not below section title)
* support both jpg and png avatars
* add docinfo support
* add navigation links in meta, e.g.,

  <link rel="up" href="#{node.attr 'up-uri'}" title="#{node.attr 'up-title'}"/>
  <link rel="prev" href="#{node.attr 'prev-uri'}" title="#{node.attr 'prev-title'}"/>
  <link rel="next" href="#{node.attr 'next-uri'}" title="#{node.attr 'next-title'}"/>

* add title/subtitle delimiter into HTML and hide with CSS?
* use less side padding in sidebar?
* can we remove content wrapper in sidebar?
* sidebar heading not right in readmill...maybe nothing to worry about?
* manually style ordered list numbers
* reduce vertical margins around basic lists (partially addressed via "brief" class)
* use float trick to fix line spacing for primary title like with the subtitle
* better handling of title without subtitle, particularly HTML and CSS
* add pink theme: http://designplus.co/en/designplus
* customize id of <item> elements in epub manifest?

//^

.CLI
* augment Asciidoctor::Cli::Options with --validate and --extract options, pass on as attributes

//^

.Asciidoctor
* patch sanitize of any section or block title into Asciidoctor
* generate id for chapter <= make part of Asciidoctor parsing API
* patch Asciidoctor to replace smart quotes w/ unicode chars instead of entities (glyph replacement mode)

//^

== REVIEW

* conversion of single file (no master document)
* package images referenced by content
* do we need the SVG property if the HTML links to an SVG document?
* how custom CSS is specified

== NOTES

* content must be XHTML (not HTML)
* Aldiko uses the image on the cover page (or a screenshot of the cover page) as the image in the bookshelf
* use -webkit-transform: translate/translateX/translateY to move objects from origin by relative distances (alternative to relative positioning, which is not permitted on Kindle)
* don't need attributes above header in sub-documents anymore (except for PDF; we'll cross that bridge when we get to it)
* vw is 1% of viewport width (see http://dev.opera.com/articles/view/css-viewport-units/)
* rhythm: 1.5, 1.25, 1.2, 1.05, 1
* webkit gets confused about how to justify text for mixed content (adjacent character data and inline elements)
  - wrap character data to solve
  - alternatively, can use zero-width space (&#8203;) immediately after inline element to signal a separation
* Kindle won't accept fonts that are less than 1K (typically can't create a font with just one or two characters)
* Control+Shift+u to type in a unicode sequent, then press enter to accept
* Calibre gets confused when there are local fonts that closely match font in stylesheet, uses them over embedded styles (in particular M+ weights)
* iBooks info: http://authoradventures.blogspot.com/2013/08/ibooks-tutorial-update-version-30.html
* selector for all prose text (including symbols)

 body p, ul, ol, li, dl, dt, dd, figcaption, caption, footer,
 table.table th, table.table td, div.verse .attribution {}

* selector for prose sentences / phrases

 body p, li, dd, figcaption, caption, th, td, blockquote > footer {}
